 @echo off
@cd/d "C:\XuanZhi\LDPlayer"
@cd/d "D:\XuanZhi\LDPlayer"
@cd/d "E:\XuanZhi\LDPlayer"
@cd/d "F:\XuanZhi\LDPlayer"
@cd/d "Y:\XuanZhi\LDPlayer"
dnconsole.exe killapp --index 0 --packagename "com.vng.pubgmobile"
dnconsole.exe killapp --index 0 --packagename "com.tencent.ig"
dnconsole.exe killapp --index 0 --packagename "com.pubg.krmobile"
dnconsole.exe killapp --index 0 --packagename "com.rekoo.pubgm"
adb -s 0 "mount -o remount,rw /"
adb -s 0 "mount -o remount,rw /system"
adb -s 0 "mount -o remount,rw /data"
adb -s 0 "mount -o remount,rw /data/data"
adb -s 0 "/data/data/com.tencent.ig/files/"
adb -s 0 "busybox mount --bind /root /data/data/com.tencent.ig/files/tss_tmp"
adb -s 0 "/data/data/com.vng.pubgmobile/files/"
adb -s 0 "busybox mount --bind /root /data/data/com.vng.pubgmobile/files/tss_tmp"
adb -s 0 "/data/data/com.pubg.krmobile/files/"
adb -s 0 "busybox mount --bind /root /data/data/com.pubg.krmobile/files/tss_tmp"
adb -s 0 "/data/data/com.rekoo.pubgm/files/"
adb -s 0 "busybox mount --bind /root /data/data/com.rekoo.pubgm/files/tss_tmp"
adb -s 0 "mount -o remount,rw /"
adb -s 0 "mount -o remount,rw /system"
adb -s 0 "mount -o remount,rw /data"
adb -s 0 "mount -o remount,rw /data/data"
adb -s 0 "mount -o remount,rw /"
adb -s 0 "mount -o remount,rw /system"
adb -s 0 "mount -o remount,rw /dev"
adb -s 0 "chattr -i /data/data/com.vng.pubgmobile/files/tss_tmp"
adb -s 0 "chattr -i /data/data/com.tencent.ig/files/tss_tmp"
adb -s 0 "chattr -i /data/data/com.pubg.krmobile/files/tss_tmp"
adb -s 0 "chattr -i /data/data/com.rekoo.pubgm/files/tss_tmp"
adb -s 0 "iptables -F"
adb -s 0 "rm -rf /data/data/com.vng.pubgmobile/files/tss_tmp"
adb -s 0 "rm -rf /data/data/com.pubg.krmobile/files/tss_tmp"
adb -s 0 "rm -rf /data/data/com.rekoo.pubgm/files/tss_tmp"
adb -s 0 "rm -rf /data/data/com.tencent.ig/files/tss_tmp"
adb -s 0 "mount -o rw,remount /lib"
adb -s 0 "mount -o rw,remount /system"
adb -s 0 "mount -o rw,remount /data/data"
adb -s 0 "mount -o remount,rw /"
adb -s 0 "rm -rf /data/data/com.tencent.ig/app_bugly"
adb -s 0 "rm -rf /data/data/com.tencent.ig/cache"
adb -s 0 "rm -rf /data/data/com.tencent.ig/app_crashrecord"
adb -s 0 "rm -rf /data/data/com.tencent.ig/code_cache"
adb -s 0 "rm -rf /data/data/com.tencent.ig/no_backup"
adb -s 0 "rm -rf /data/data/com.tencent.ig/files"
adb -s 0 "rm -rf /data/data/com.vng.pubgmobile/app_bugly"
adb -s 0 "rm -rf /data/data/com.vng.pubgmobile/cache"
adb -s 0 "rm -rf /data/data/com.vng.pubgmobile/app_crashrecord"
adb -s 0 "rm -rf /data/data/com.vng.pubgmobile/code_cache"
adb -s 0 "rm -rf /data/data/com.vng.pubgmobile/no_backup"
adb -s 0 "rm -rf /data/data/com.vng.pubgmobile/files"
adb -s 0 "rm -rf /data/data/com.pubg.krmobile/app_bugly"
adb -s 0 "rm -rf /data/data/com.pubg.krmobile/cache"
adb -s 0 "rm -rf /data/data/com.pubg.krmobile/app_crashrecord"
adb -s 0 "rm -rf /data/data/com.pubg.krmobile/code_cache"
adb -s 0 "rm -rf /data/data/com.pubg.krmobile/no_backup"
adb -s 0 "rm -rf /data/data/com.pubg.krmobile/files"
adb -s 0 "rm -rf /data/data/com.rekoo.pubgm/app_bugly"
adb -s 0 "rm -rf /data/data/com.rekoo.pubgm/cache"
adb -s 0 "rm -rf /data/data/com.rekoo.pubgm/app_crashrecord"
adb -s 0 "rm -rf /data/data/com.rekoo.pubgm/code_cache"
adb -s 0 "rm -rf /data/data/com.rekoo.pubgm/no_backup"
adb -s 0 "rm -rf /data/data/com.rekoo.pubgm/files"
adb -s 0 "mv /system/lib/libhoudini.so1 /system/lib/libhoudini.so"
adb -s 0 "mv /system/lib/arm/liblog.so1 /system/lib/arm/liblog.so"
adb -s 0 "mv /system/lib/arm/libstdc++.so1 /system/lib/arm/libstdc++.so"
adb -s 0 "mv /system/lib/arm/nb/libEGL.so1 /system/lib/arm/nb/libEGL.so"
adb -s 0 "mv /system/lib/arm/nb/libGLESv1_CM.so1 /system/lib/arm/nb/libGLESv1_CM.so"
adb -s 0 "mv /system/lib/arm/nb/libGLESv2.so1 /system/lib/arm/nb/libGLESv2.so"
adb -s 0 "mv /system/lib/arm/nb/libOpenSLES.so1 /system/lib/arm/nb/libOpenSLES.so"
adb -s 0 "mv /system/lib/arm/nb/libandroid.so1 /system/lib/arm/nb/libandroid.so"
adb -s 0 "mv /system/lib/arm/nb/libc.so1 /system/lib/arm/nb/libc.so"
adb -s 0 "mv /system/lib/arm/nb/libdl.so1 /system/lib/arm/nb/libdl.so"
adb -s 0 "mv /system/lib/arm/nb/libm.so1 /system/lib/arm/nb/libm.so"
adb -s 0 "mv /system/lib/arm/nb/libz.so1 /system/lib/arm/nb/libz.so"
adb -s 0 "mv /dev/vboxguest1 /dev/vboxguest"
adb -s 0 "mv /dev/vboxuser1 /dev/vboxuser"
adb -s 0 "mv /system/lib/libldutils.so1 /system/lib/libldutils.so"
adb -s 0 "busybox mount --bind /sbin /sys/module"
adb -s 0 "busybox mount --bind /sbin /sys/devices/virtual/misc"
adb -s 0 "busybox mount --bind /sbin /system/etc/security/cacerts"
adb -s 0 "rm -rf /dev/you"
adb -s 0 "chmod -R 777 /dev/you"
@cd/d "C:\LDPlayer\LDPlayer4.0"
@cd/d "C:\LDPlayer\LDPlayer9"
@cd/d "D:\LDPlayer\LDPlayer4.0"
@cd/d "D:\LDPlayer\LDPlayer9"
@cd/d "E:\LDPlayer\LDPlayer4.0"
@cd/d "E:\LDPlayer\LDPlayer9"
@cd/d "F:\LDPlayer\LDPlayer4.0"
@cd/d "F:\LDPlayer\LDPlayer9"
@cd/d "Y:\LDPlayer\LDPlayer4.0"
@cd/d "Y:\LDPlayer\LDPlayer9"
 
dnconsole quit --index 1 
iptables -D INPUT -s lobby.igamecj.com -j DROP 
ld  -s 0 killall com.tencent.ig 
ld  -s 0 am force-stop com.tencent.ig 
iptables -D INPUT -s krlobby.igamecj.com -j DROP 
ld  -s 0 killall com.pubg.krmobile 
ld  -s 0 am force-stop com.pubg.krmobile 
iptables -D INPUT -s twlobby.igamecj.com -j DROP 
ld  -s 0 killall com.rekoo.pubgm 
ld  -s 0 am force-stop com.rekoo.pubgm 
iptables -D INPUT -s vnglobby.igamecj.com -j DROP 
ld  -s 0 killall com.vng.pubgmobile 
ld  -s 0 am force-stop com.vng.pubgmobile
