@cd/d "C:\LDPlayer\LDPlayer4.0"
@cd/d "C:\LDPlayer\LDPlayer9"
@cd/d "D:\LDPlayer\LDPlayer4.0"
@cd/d "D:\LDPlayer\LDPlayer9"
@cd/d "E:\LDPlayer\LDPlayer4.0"
@cd/d "E:\LDPlayer\LDPlayer9"
@cd/d "F:\LDPlayer\LDPlayer4.0"
@cd/d "F:\LDPlayer\LDPlayer9"
@cd/d "Y:\LDPlayer\LDPlayer4.0"
@cd/d "Y:\LDPlayer\LDPlayer9"
dnconsole launch --index 0